import express from "express";
import routerUse from "./routers/user.route.js";
import routerAuth from "./routers/auth.route.js";
import routerClub from "./routers/club.route.js";
const app = express();
app.use(express.json());
app.use("/user", routerUse);
app.use("/auth", routerAuth);
app.use("/club", routerClub);
export default app;
